spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MySql1672943850
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 禁用警告
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    encoding: utf-8
#  security:
#    user:
#      name: admin
#      password: 123123
#  mvc:
#    hidden-method:
#      filter:
#        enabled: true