spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MySQL1672943850
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Silent
    #    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    session:
      # 1800 秒无操作后再操作需要重新登录账号
      timeout: 1800
#  thymeleaf:
#    encoding: utf-8
#  mvc:
#    hidden-method:
#      filter:
#        enabled: true